// Records the schema the Node server leaves in its SQLite database, for the
// adoption tests (internal/database/adopt). Nothing here is written by hand:
// every statement in node-schema.json is what SQLite stores in sqlite_schema
// after the real apps/server/src/db.ts initializeDatabase ran on it.
//
// Two variants:
//
//   fresh   a database created by the current Node server;
//   legacy  a database first created by the earliest recorded Node schema
//           (commit e08f508: articles without source/source_url) that also
//           had a minimal subscribers table, then opened by the current Node
//           server, so Node's own ALTER TABLE statements append the missing
//           columns at the end.
//
// No network, no listener, no real database: both databases are in memory,
// and seeding is off. Run from the repository root of a checkout whose
// apps/server dependencies are installed (NODE_SERVER_ROOT overrides the
// apps/server location, for example when running from a git worktree):
//
//   apps/server/node_modules/.bin/tsx \
//     apps/server-go/internal/database/adopt/testdata/record-node-schema.ts \
//     apps/server-go/internal/database/adopt/testdata
import { writeFileSync } from "node:fs";
import path from "node:path";

const serverRoot = process.env.NODE_SERVER_ROOT || path.resolve(__dirname, "../../../../../server");
const outputDir = process.argv[2] || __dirname;

// eslint-disable-next-line @typescript-eslint/no-require-imports
const Database = require(path.join(serverRoot, "node_modules/better-sqlite3"));
// eslint-disable-next-line @typescript-eslint/no-require-imports
const dbModule = require(path.join(serverRoot, "src/db.ts"));

// The articles table of the earliest recorded Node schema (git show
// e08f508:apps/server/src/db.ts), before source and source_url existed.
const LEGACY_ARTICLES = `CREATE TABLE articles (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      excerpt TEXT NOT NULL DEFAULT '',
      content TEXT NOT NULL DEFAULT '',
      featured_image TEXT,
      category_id INTEGER NOT NULL,
      author_id INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft', 'published', 'scheduled')),
      published_at TEXT,
      meta_title TEXT,
      meta_description TEXT,
      view_count INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (category_id) REFERENCES categories(id),
      FOREIGN KEY (author_id) REFERENCES authors(id)
    )`;

// The smallest subscribers table initializeDatabase upgrades: every column
// db.ts knows how to add is missing, so all seven ALTER TABLE statements run.
const LEGACY_SUBSCRIBERS = `CREATE TABLE subscribers (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT NOT NULL UNIQUE
    )`;

type SchemaObject = { type: string; name: string; tbl_name: string; sql: string };

function dump(db: { prepare: (sql: string) => { all: () => unknown[] } }): SchemaObject[] {
  return db
    .prepare(
      "SELECT type, name, tbl_name, sql FROM sqlite_schema WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL ORDER BY rowid",
    )
    .all() as SchemaObject[];
}

function record(prepare?: string[]): SchemaObject[] {
  const db = new Database(":memory:");
  db.pragma("foreign_keys = ON");
  for (const statement of prepare ?? []) db.exec(statement);
  dbModule.initializeDatabase(db, { seedDefaults: false });
  const objects = dump(db);
  db.close();
  return objects;
}

const versions = (() => {
  const db = new Database(":memory:");
  const sqlite = (db.prepare("SELECT sqlite_version() AS v").get() as { v: string }).v;
  db.close();
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const betterSqlite = require(path.join(serverRoot, "node_modules/better-sqlite3/package.json")).version;
  return { node: process.version, betterSqlite3: betterSqlite, sqlite };
})();

const output = {
  note:
    "Generated by record-node-schema.ts from apps/server/src/db.ts initializeDatabase (seedDefaults: false). Do not edit by hand.",
  ...versions,
  fresh: record(),
  legacy: record([LEGACY_ARTICLES, LEGACY_SUBSCRIBERS]),
};

writeFileSync(path.join(outputDir, "node-schema.json"), `${JSON.stringify(output, null, 2)}\n`);
console.log(`wrote ${path.join(outputDir, "node-schema.json")}`);
