import type { Article, Category, Author, Media, Settings } from "@technews/shared";

export const mockAuthor: Author = {
  id: 1,
  name: "Admin",
  email: "admin@technews.com",
  avatar: null,
  bio: "Site administrator",
  role: "admin",
};

export const mockCategories: Category[] = [
  { id: 1, name: "Artificial Intelligence", slug: "ai", description: "AI, machine learning, and deep learning news", color: "#8b5cf6" },
  { id: 2, name: "Programming", slug: "programming", description: "Languages, frameworks, and developer tools", color: "#3b82f6" },
  { id: 3, name: "Startups", slug: "startups", description: "Startup news, funding rounds, and entrepreneurship", color: "#10b981" },
  { id: 4, name: "Hardware", slug: "hardware", description: "Chips, devices, and consumer electronics", color: "#f59e0b" },
  { id: 5, name: "Science", slug: "science", description: "Scientific discoveries and research breakthroughs", color: "#ec4899" },
  { id: 6, name: "Industry", slug: "industry", description: "Big tech companies and industry trends", color: "#6366f1" },
];

export const mockArticles: (Article & { author: Author; category: Category })[] = [
  {
    id: 1,
    title: "OpenAI Unveils GPT-5 with Unprecedented Reasoning Capabilities",
    slug: "openai-unveils-gpt-5-reasoning",
    excerpt: "The latest model from OpenAI demonstrates significant improvements in multi-step reasoning, code generation, and scientific analysis.",
    content: "# OpenAI Unveils GPT-5\n\nOpenAI has officially released GPT-5, marking a major leap forward in large language model capabilities...\n\n## Key Improvements\n\n- Multi-step reasoning accuracy improved by 40%\n- Native code execution and debugging\n- Real-time web browsing integration\n\n## Industry Impact\n\nAnalysts predict this release will reshape the competitive AI landscape...",
    featured_image: null,
    category_id: 1,
    author_id: 1,
    status: "published",
    published_at: "2025-01-15T10:00:00Z",
    meta_title: "GPT-5 Launch: OpenAI's Most Advanced Model Yet",
    meta_description: "OpenAI releases GPT-5 with groundbreaking reasoning capabilities that outperform previous models by significant margins.",
    created_at: "2025-01-14T08:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
    author: mockAuthor,
    category: mockCategories[0],
  },
  {
    id: 2,
    title: "Rust 2.0 Released: The Language That Changed Systems Programming",
    slug: "rust-2-0-released",
    excerpt: "After years of development, Rust 2.0 brings async improvements, better compile times, and a revamped trait system.",
    content: "# Rust 2.0 Released\n\nThe Rust team has announced the release of Rust 2.0...",
    featured_image: null,
    category_id: 2,
    author_id: 1,
    status: "published",
    published_at: "2025-01-14T14:00:00Z",
    meta_title: null,
    meta_description: null,
    created_at: "2025-01-13T16:00:00Z",
    updated_at: "2025-01-14T14:00:00Z",
    author: mockAuthor,
    category: mockCategories[1],
  },
  {
    id: 3,
    title: "Stripe Acquires AI Startup for $2.1 Billion",
    slug: "stripe-acquires-ai-startup",
    excerpt: "The payments giant makes its largest acquisition to date, betting big on AI-powered fraud detection.",
    content: "# Stripe Acquires AI Startup\n\nStripe announced today that it has acquired...",
    featured_image: null,
    category_id: 3,
    author_id: 1,
    status: "published",
    published_at: "2025-01-13T09:00:00Z",
    meta_title: null,
    meta_description: null,
    created_at: "2025-01-12T20:00:00Z",
    updated_at: "2025-01-13T09:00:00Z",
    author: mockAuthor,
    category: mockCategories[2],
  },
  {
    id: 4,
    title: "Apple's M5 Chip Benchmarks Leak: 60% Faster Than M4",
    slug: "apple-m5-chip-benchmarks-leak",
    excerpt: "Leaked benchmarks suggest Apple's next-gen silicon will deliver massive performance gains across all workloads.",
    content: "# Apple M5 Benchmarks Leak\n\nPreliminary benchmark results for Apple's upcoming M5 processor...",
    featured_image: null,
    category_id: 4,
    author_id: 1,
    status: "draft",
    published_at: null,
    meta_title: null,
    meta_description: null,
    created_at: "2025-01-15T11:00:00Z",
    updated_at: "2025-01-15T11:00:00Z",
    author: mockAuthor,
    category: mockCategories[3],
  },
  {
    id: 5,
    title: "CRISPR Breakthrough Enables Single-Injection Gene Therapy",
    slug: "crispr-single-injection-gene-therapy",
    excerpt: "Researchers achieve a major milestone in gene therapy with a new CRISPR delivery mechanism that requires only one injection.",
    content: "# CRISPR Breakthrough\n\nA team of researchers has developed a new approach...",
    featured_image: null,
    category_id: 5,
    author_id: 1,
    status: "published",
    published_at: "2025-01-12T16:00:00Z",
    meta_title: null,
    meta_description: null,
    created_at: "2025-01-11T10:00:00Z",
    updated_at: "2025-01-12T16:00:00Z",
    author: mockAuthor,
    category: mockCategories[4],
  },
  {
    id: 6,
    title: "Google Announces Quantum Computing Milestone: 1000 Qubit Processor",
    slug: "google-quantum-1000-qubit",
    excerpt: "Google's new quantum processor reaches 1000 qubits with error correction, bringing practical quantum computing closer to reality.",
    content: "# Google Quantum Computing Milestone\n\nGoogle has announced a breakthrough in quantum computing...",
    featured_image: null,
    category_id: 6,
    author_id: 1,
    status: "scheduled",
    published_at: "2025-01-20T10:00:00Z",
    meta_title: "Google Achieves 1000 Qubit Quantum Milestone",
    meta_description: "Google's latest quantum processor reaches 1000 qubits with error correction capabilities.",
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-01-15T09:00:00Z",
    author: mockAuthor,
    category: mockCategories[5],
  },
  {
    id: 7,
    title: "The Rise of Local-First Software: Why Developers Are Rethinking the Cloud",
    slug: "rise-of-local-first-software",
    excerpt: "A growing movement of developers is building software that works offline-first, challenging the cloud-only paradigm.",
    content: "# The Rise of Local-First Software\n\nFor the past decade, the cloud has been king...",
    featured_image: null,
    category_id: 2,
    author_id: 1,
    status: "draft",
    published_at: null,
    meta_title: null,
    meta_description: null,
    created_at: "2025-01-14T15:00:00Z",
    updated_at: "2025-01-14T15:00:00Z",
    author: mockAuthor,
    category: mockCategories[1],
  },
  {
    id: 8,
    title: "Anthropic Raises $5B Series D at $60B Valuation",
    slug: "anthropic-series-d-funding",
    excerpt: "The AI safety company secures massive new funding round as enterprise demand for Claude surges.",
    content: "# Anthropic Raises $5B\n\nAnthropic, the AI safety startup behind Claude...",
    featured_image: null,
    category_id: 3,
    author_id: 1,
    status: "published",
    published_at: "2025-01-11T12:00:00Z",
    meta_title: null,
    meta_description: null,
    created_at: "2025-01-11T08:00:00Z",
    updated_at: "2025-01-11T12:00:00Z",
    author: mockAuthor,
    category: mockCategories[2],
  },
  {
    id: 9,
    title: "New NVIDIA GPU Architecture Targets AI Training Efficiency",
    slug: "nvidia-new-gpu-architecture-ai",
    excerpt: "NVIDIA's next-generation architecture promises 3x better AI training performance per watt.",
    content: "# New NVIDIA GPU Architecture\n\nNVIDIA has previewed its next-generation GPU architecture...",
    featured_image: null,
    category_id: 4,
    author_id: 1,
    status: "scheduled",
    published_at: "2025-01-22T10:00:00Z",
    meta_title: null,
    meta_description: null,
    created_at: "2025-01-15T14:00:00Z",
    updated_at: "2025-01-15T14:00:00Z",
    author: mockAuthor,
    category: mockCategories[3],
  },
  {
    id: 10,
    title: "DeepMind Solves New Class of Mathematical Problems with AI",
    slug: "deepmind-solves-math-problems",
    excerpt: "Google DeepMind's latest research demonstrates AI systems solving previously unsolved mathematical conjectures.",
    content: "# DeepMind Solves Mathematical Problems\n\nResearchers at Google DeepMind have published a paper...",
    featured_image: null,
    category_id: 1,
    author_id: 1,
    status: "draft",
    published_at: null,
    meta_title: null,
    meta_description: null,
    created_at: "2025-01-15T16:00:00Z",
    updated_at: "2025-01-15T16:00:00Z",
    author: mockAuthor,
    category: mockCategories[0],
  },
];

export const mockMedia: Media[] = [
  {
    id: 1,
    filename: "gpt5-hero.jpg",
    url: "/placeholder/800/450/6366f1",
    mime_type: "image/jpeg",
    size: 245760,
    uploaded_at: "2025-01-14T08:00:00Z",
  },
  {
    id: 2,
    filename: "rust-logo.png",
    url: "/placeholder/800/450/3b82f6",
    mime_type: "image/png",
    size: 102400,
    uploaded_at: "2025-01-13T16:00:00Z",
  },
  {
    id: 3,
    filename: "stripe-acquisition.jpg",
    url: "/placeholder/800/450/10b981",
    mime_type: "image/jpeg",
    size: 384000,
    uploaded_at: "2025-01-12T20:00:00Z",
  },
  {
    id: 4,
    filename: "m5-chip-render.png",
    url: "/placeholder/800/450/f59e0b",
    mime_type: "image/png",
    size: 512000,
    uploaded_at: "2025-01-15T11:00:00Z",
  },
  {
    id: 5,
    filename: "crispr-lab.jpg",
    url: "/placeholder/800/450/ec4899",
    mime_type: "image/jpeg",
    size: 296000,
    uploaded_at: "2025-01-11T10:00:00Z",
  },
  {
    id: 6,
    filename: "quantum-processor.png",
    url: "/placeholder/800/450/8b5cf6",
    mime_type: "image/png",
    size: 448000,
    uploaded_at: "2025-01-15T09:00:00Z",
  },
];

export const mockSettings: Settings = {
  site_name: "TechNews",
  site_description: "The latest news in AI, programming, startups, and technology",
  social_twitter: "https://x.com/technews",
  social_linkedin: "https://linkedin.com/company/technews",
  social_github: "https://github.com/technews",
  newsletter_enabled: true,
  newsletter_provider: "mailchimp",
  newsletter_webhook_url: "https://api.mailchimp.com/webhook/abc123",
};
